name: Generate meta info

on: [ push, pull_request, pull_request_target ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Run generator
      run: python ${{ github.workspace }}/CommonLibF4/scripts/glob_files.py

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: regenerate meta files
